apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  #make connection between service and pods
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
  # metadata for pods
    metadata:
      labels:
        app: nginx
    # blueprint for each pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80
